### PR TITLE
if a restored purchase, return original transaction ID

### PR DESCRIPTION
**Pull request by tenpn**
because the new transaction ID isn't found in the app's receipt, so returning that doesn't allow calling apps to externally re-verify the purchase.

More discussion: https://github.com/soomla/unity3d-store/issues/429

Have copied the generated .a files to my unity project (that uses soomla unity) and successfully verified a restored purchase and a new purchase.

### CODE REVIEW

**Comment by refaelos** [comment]
Can you explain exactly why you need to original transaction id?
What's the process in which you're using it?

**Comment by tenpn** [comment]
Dude, I linked to the discussion, which you were personally involved with. 

- an iOS restored purchase comes with a transaction ID and a _restored_ transaction ID
- soomla returns the former to unity, along with the app receipt
- the app receipt only includes a record of the _restored_ transaction ID
- therefore I can't match the two up and verify the transaction on my custom server

this fix returns the restored transaction ID, so verification with the receipt can work.

**Comment by tenpn** [comment]
any progress on this? anything?

**Comment by tenpn** [comment]
(made some changes for a missing edge case, see log for more details)

**Comment by tenpn** [comment]
Ah. that seems sensible.

**Comment by refaelos** [comment]
Ok do you want to do it or do we add it to our task list?

**Comment by tenpn** [comment]
No, I'm not doing it.

**Comment by refaelos** [comment]
Made the changes.
I need your help testing it. I'm guessing you're using the unity packages ...

Download and import: https://github.com/soomla/unity3d-store/blob/master/soomla-unity3d-store.unitypackage
And see which variables you're getting now in the "extra" Dictionary.

**Comment by tenpn** [comment]
My project was on soomla unity 1.7.16. I installed the store package above, but got xcode compile failures. I installed the lastest core package from github too and still got compile fails. The compile fails were because of duplicate symbols in libSoomlaIOSCore.a and libSOomlaIOSStore.a, eg Schedule.o, KeyValueStorage.o, and Reward.o.

**Comment by refaelos** [comment]
@vedi can you check this?

**Pull request closed without merging**
