### PR TITLE
Fix nil bug of SoomlaVerification when refreshing the receipt data

### PR DESCRIPTION
**Pull request by emperor1412**
- Fix nill bug when calling this [[SKPaymentQueue defaultQueue] finishTransaction: transaction];

- NSJSonSerialization can not parse NSDate and NSURL, so I convert them into NSString :

<code>
   NSString *transactionDate = transaction.transactionDate ? [NSDateFormatter localizedStringFromDate:transaction.transactionDate
                                                                                             dateStyle:NSDateFormatterShortStyle
                                                                                             timeStyle:NSDateFormatterFullStyle] : @"";

    NSString *transactionDateOriginal = transaction.originalTransaction ? [NSDateFormatter localizedStringFromDate:[transaction.originalTransaction transactionDate]
                                                                                                         dateStyle:NSDateFormatterShortStyle
                                                                                                         timeStyle:NSDateFormatterFullStyle] : transactionDate;

- SKReceiptRefreshRequest *req = [[SKReceiptRefreshRequest alloc] initWithReceiptProperties:nil];
                req.delegate = self;
                [req start];
</code>

When callback of SKReceiptRefreshRequest get called, instance of SoomlaVerification has been destroyed. So I make SoomlaVerification singleton so that it's always exist ready to process the callbacks of SKReceiptRefreshRequest.

### CODE REVIEW

**Comment by refaelos** [comment]
@emperor1412 that's a good one.

Having SoomlaVerification as singleton is problematic. The reason we're creating an instance for every run of verification is that there can be multiple runs at once (in cases of restoring transactions for example).

Fix that so I can merge this PR.

**Comment by emperor1412** [comment]
@refaelos I'm working with server side verification, 
<code> if (responseCode==200 && verifiedNum) {
        
        verified = [verifiedNum boolValue];
        if (!verified) {
            NSNumber* emptyResponse = (NSNumber*)[responseDict objectForKey:@"emptyResponse"];
            BOOL needRefresh = [emptyResponse boolValue];
            if (needRefresh && tryAgain) {  
</code>

can you share soomla server source code, I'm stuck at the idea of  "emptyResponse". I would like to know more about when server will return this

**Comment by refaelos** [comment]
Why do you need to work on the verification to this granularity?

The code pretty much takes care of everything.

Make sure you're merged with the latest version of master. There were some changes.

**Comment by emperor1412** [comment]
We are having verification process happen on our server so that the server can update user information in database. We would like to re-use this verification class of Soomla as much as possible. But point is the API guy is not sure when to return  "emptyResponse" in the response. 

When we do testing verification with soomla server, there are many times when "emptyResponse" is return to client and thus fall into the block of requesting for the receipt again (SKReceiptRefreshRequest), and eventually crash the app when the call back of SKReceiptRefreshRequest get called and the SoomlaVerification instance that initiate the SKReceiptRefreshRequest has been destroyed.

So it would be clear if we can see the server verification code and know when "emptyResponse" is returned.

**Comment by refaelos** [comment]
"emptyResponse" is returned when Apple's server is telling us that there's an empty in_app array in the receipt. In these cases we try to refresh the receipt on the device and do the verification again.

The SoomlaVerification instance will not be terminated with the latest code from master. We've fixed that.

Btw, What company are you working for?

**Comment by emperor1412** [comment]
Thanks for the "emptyResponse" logic. I'm working for a company that do outsourcing in Viet Nam.
I also use NSMutableArray to fix the "SoomlaVerification instance nil" as in your commit, but I put the variable in SoomlaVerification.m file, not in SoomlaStore.m.
I'm testing on this and observe that when SKReceiptRefreshRequest get called, eventually [self verifyData] will be called, and this time all the instance variables of SoomlaVerification (responseData, purchasable, transaction) have been destroyed so it crash again. 

I'm trying to fix by this in SoomlaVerification.h to see if the issue can be fixed
<code>
 __strong NSMutableData *responseData;
    int responseCode;
    __strong PurchasableVirtualItem *purchasable;
    __strong SKPaymentTransaction* transaction;
</code>

**Comment by refaelos** [comment]
Ok. Let me know if it works.

Also, can you send me an email at refael@soom.la ?

**Comment by emperor1412** [comment]
Hi, here is the code when client received response from verification server:

```objective-c
- (void)connectionDidFinishLoading:(NSURLConnection *)connection {
    NSString* dataStr = [[NSString alloc] initWithData:responseData encoding:NSUTF8StringEncoding];
    NSNumber* verifiedNum = nil;
    
    
    if ([dataStr isEqualToString:@""]) {
        LogError(TAG, @"There was a problem when verifying. Got an empty response. Will try again later.");
        [StoreEventHandling postUnexpectedError:ERR_VERIFICATION_FAIL forObject:self];
        return;
    }

    NSDictionary* responseDict = NULL;
    @try {
        responseDict = [SoomlaUtils jsonStringToDict:dataStr];
        verifiedNum = (NSNumber*)[responseDict objectForKey:@"verified"];
    } @catch (NSException* e) {
        LogError(TAG, @"There was a problem when verifying when handling response.");
    }
    
    BOOL verified = NO;
    if (responseCode==200  && verifiedNum) {
        
        verified = [verifiedNum boolValue];
        if (!verified) {
            NSNumber* emptyResponse = (NSNumber*)[responseDict objectForKey:@"emptyResponse"];
            BOOL needRefresh = [emptyResponse boolValue];
            if (needRefresh && tryAgain) {
                LogDebug(TAG, @"Receipt refresh needed.");
                tryAgain = NO;
                SKReceiptRefreshRequest *req = [[SKReceiptRefreshRequest alloc] initWithReceiptProperties:nil];
                req.delegate = self;
                [cacheRetryRequestReceipt addObject:self];
                [req start];

                // we return here ...
                return;
            }
        }
        [StoreEventHandling postMarketPurchaseVerification:verified forItem:purchasable andTransaction:transaction forObject:self];
    } else {
        NSString* errorMsg = @"";
        if (responseDict) {
            @try {
                id errorObject = [responseDict objectForKey:@"error"];
                if([errorObject isKindOfClass:[NSDictionary class]]) {
                    errorMsg = [errorObject objectForKey:@"message"];
                }
                else if([errorObject isKindOfClass:[NSString class]]){
                    errorMsg = (NSString *) errorObject;
                }
                else {
                    errorMsg = @"Unknown Error";
                }

            } @catch (NSException* e) {
                LogError(TAG, @"There was a problem when verifying when handling response.");
            }
        }
        
        if ([errorMsg isEqualToString:@"ECONNRESET"]) {
            LogError(TAG, @"It appears that the iTunes servers are down. We can't verify this receipt.");
        }
        
        LogError(TAG, ([NSString stringWithFormat:@"There was a problem when verifying (%@). Will try again later.", errorMsg]));
        [StoreEventHandling postUnexpectedError:ERR_VERIFICATION_TIMEOUT forObject:self];
    }
}
```

the response from soomla server will usually look like this :
```json
    "success": 0,
    "verified": 0,
    "error": "The data in the receipt-data property was malformed or missing.",
    "emptyResponse": false
```

In this method, there is <code>   if (responseCode==200  && verifiedNum) { </code> which do the check based on responseCode, there is no line of code get the "success" from response which make "success" useless. 

So what is the purpose of "success" ?

I though "success" is used to tell the client side that the verification server was able to talk to apple server, and "verified" will tell client that whether the receipt is valid or not. The "responseCode" is just the status when client talk to verification server, it's not the status when verification server talked to apple server. Is my assumption correct ?

**Comment by refaelos** [comment]
Not entirely. "success" is not important in the response. The response code is the HTTP status of the response. If there was an error on the server then the code will probably be 500.

Is your PR ready for merge?

**Comment by emperor1412** [comment]
yes, it's ready to merge, but I modified it to suit the need for my projects. So you may find some changes that is not so generic like this part

```objective-c

    BOOL verified = NO;
    if (responseCode==200 && successNum && [successNum boolValue] && verifiedNum) {
        
        verified = [verifiedNum boolValue];
        if (!verified) {
            NSNumber* emptyResponse = (NSNumber*)[responseDict objectForKey:@"emptyResponse"];
            BOOL needRefresh = [emptyResponse boolValue];
            if (needRefresh && tryAgain) {
                LogDebug(TAG, @"Receipt refresh needed.");
                tryAgain = NO;
                SKReceiptRefreshRequest *req = [[SKReceiptRefreshRequest alloc] initWithReceiptProperties:nil];
                req.delegate = self;
                [cacheRetryRequestReceipt addObject:self];
                [req start];

                // we return here ...
                return;
            }
        }
        [StoreEventHandling postMarketPurchaseVerification:verified forItem:purchasable andTransaction:transaction forObject:self];
    } else {
        NSString* errorMsg = @"";
        if (responseDict) {
            @try {
                id errorObject = [responseDict objectForKey:@"error"];
                if([errorObject isKindOfClass:[NSDictionary class]]) {
                    errorMsg = [errorObject objectForKey:@"message"];
                }
                else if([errorObject isKindOfClass:[NSString class]]){
                    errorMsg = (NSString *) errorObject;
                }
                else {
                    errorMsg = @"Unknown Error";
                }

            } @catch (NSException* e) {
                LogError(TAG, @"There was a problem when verifying when handling response.");
            }
        }
        
        if ([errorMsg isEqualToString:@"ECONNRESET"]) {
            LogError(TAG, @"It appears that the iTunes servers are down. We can't verify this receipt.");
        }
        
        LogError(TAG, ([NSString stringWithFormat:@"There was a problem when verifying (%@). Will try again later.", errorMsg]));
        [StoreEventHandling postUnexpectedError:ERR_VERIFICATION_TIMEOUT forObject:self];
    }
}

```

**Comment by emperor1412** [comment]
There are also changes that are made correspondingly in unity-store repo. If you want to merge this emperor1412/ios-store, you may want to merge changes from emperor1412/unity-store as well so that I will create PR for that branch

**Comment by refaelos** [comment]
@emperor1412 I wrote you a few comments in the code. Take a look.

**Comment by emperor1412** [comment]
Hi, I did updated the "success" variables

**Comment by refaelos** [comment]
This PR has been through many changes :)
Can you close it, merge the code from master and PR again? I want to go over it in one batch.

**Pull request closed without merging**
