### PR TITLE
Manually retrying unfinished transactions after billing service loaded

### PR DESCRIPTION
**Pull request by zentuit**
Currently unfinished transactions don't get the opportunity to finish on start up as the SKPaymentQueue observer is not hooked up when the call is made.

This pull request is a companion to https://github.com/soomla/unity3d-store/pull/437

I also fixed the NSDate and NSURL serialization issue on purchases.
(I think these last 2 should be moved to Store handler, but that would require deeper changes and const strings and I wanted this up ASAP)

### CODE REVIEW

**Comment by zentuit** [comment]
@refaelos - yes this resolves the recurring login window at the beginning.

I had a thought that its possible with how Unity initializes things that there's no absolute guarantee that you can be 100% certain that the observer is initialized early enough to catch the initial paymentQueue: updatedTransactions call without inheriting from UnityAppController and overriding application:didFinishLaunchingWithOptions to put the observer there.

I think as we layer on ad networks, analytics, and other start up components the Soomla initialization gets pushed back.

I have no hard data to back that up however. But I think it makes sense.

**Comment by zentuit** [comment]
Oh @refaelos, you just pulled in SoomlaStore.m, right? That's the only file that needed to be pulled in. The others are from me pushing an alternate branch into my master

**Comment by refaelos** [comment]
@zentuit after you merge with the latest master, can you close this PR and create another one? It'll be a lot easier to read the changes this way.

**Comment by zentuit** [comment]
Redid pull request per @refaelos - https://github.com/soomla/ios-store/pull/48

**Pull request closed without merging**
